# Generated by Django 3.2 on 2021-08-02 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviegator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(editable=False, help_text='ID of title on IMDb site', max_length=18, unique=True)),
                ('type', models.CharField(choices=[('m', 'movie'), ('s', 'show')], help_text='Movie or TV show', max_length=1)),
                ('title', models.CharField(help_text='Movie / TV Show title', max_length=256)),
                ('year', models.CharField(help_text='Release year', max_length=4)),
                ('image', models.URLField(help_text='URL for poster from IMDb', max_length=1024)),
                ('details', models.CharField(help_text='Additional details about director, cast, etc.', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist', models.BooleanField(default=False)),
                ('watched', models.BooleanField(default=False)),
                ('rating', models.CharField(choices=[('0', 'not rated'), ('1', '1-star'), ('2', '2-star'), ('3', '3-star'), ('4', '4-star'), ('5', '5-star')], default='0', help_text='Rate a movie / show from 1 to 5', max_length=1)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie_details', to='moviegator.moviedb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
